substitutions:
  name: bigesp32
  friendly_name: "bigesp32"

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  - platform: esphome
    password: !secret ota_password

esphome:
  name: ${name}
  friendly_name: "${friendly_name}"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

esp32_ble_tracker:

bluetooth_proxy:
  active: true

